[project]
name = "day5-mini-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "swarnabha", email = "swarnabhadutta909@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "groq>=1.7.0",
    "pydantic>=2.13.4",
    "pypdf>=6.16.2",
    "python-docx>=1.2.0",
    "python-dotenv>=1.2.3",
    "streamlit>=1.62.0",
]

[project.scripts]
day5-mini-project = "day5_mini_project:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
