[project]
name = "day14"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "swarnabha", email = "swarnabhadutta909@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "grq>=0.1.dev1",
    "numpy>=2.4.6",
    "python-dotenv>=1.2.3",
    "qdrant-client>=1.19.0",
    "sentence-transformers>=6.0.1",
]

[project.scripts]
day14 = "day14:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
